### ISSUE TITLE
Issues in building a web based soft phone using green J library

### ISSUE THREAD

**Issue by mukeshraj8** [danleeb/GreenJ#15]
Hi
Using GreenJ library I am trying to build a web-based soft-phone.What I am trying to do is as follows:

1)I want to have an HTML page, which displays username, host and password, so that a user could register to the server through this page.

2)Once the registration is successful, my web page should diaplay the web-soft-phone using which I could make call.

Now to achieve this, I built GreenJ library under visual studio 2008 and with modification in index.html I have been successful to build a soft phone. When executed from within greenj using visual studio, the application is working fine as it is launching the Integrated browser. 

But when I use an external browser like Mozilla firefox to launch index.html it does not work. Where am I wrong? I have placed all the required DLLs and images as suggested on the webiste but to no avail. What Will I have to do for this so that I am able to launch my web page directly with external browser though which I can connect to the sip server for registration and for making calls.

Looking forward to hearing from you ASAP.

Regards,
Mukesh

**Comment by joseotaviorf** [comment]
@mukeshraj8 Is it not possible to use an external browser and have access to the SIP API. GreenJ works by wrapping a WebKit window instance and injecting the phone object inside the javascript VM running inside that window, so that the SIP API can be accessed from your js code. So, it is not an extension for common browsers, but behaves like one with extended functionality.

**Comment by mukeshraj8** [comment]
Thanks for the reply dude.
