### ISSUE TITLE
can you show us how to build GreenJ in windows 

### ISSUE THREAD

**Issue by running8Man** [danleeb/GreenJ#28]
It took me a couple of days, and it didn't work ...

![qq 20170304171506](https://cloud.githubusercontent.com/assets/24468179/23577581/3dd02788-00fe-11e7-9bcc-6ba928bcf305.png)

**Comment by danleeb** [comment]
Hi, I have not tried to compile it myself for a while now.
But I can paste in the old windows instructions for you. I'm not sure if it is of any help:


**Windows (Microsoft Visual Studio 2008)**

1. Download and install Qt (e.g. “Qt libraries 4.7.4 for Windows (VS 2008)” from http://qt.nokia.com/downloads)
2. Add an environment variable called “QTDIR” with value = “path/to/Qt” (e.g. “C:Qt”). Optional: Add “path/to/Qt/bin” to your system variable “path”, so all necessary dll files are found.
3. Download and unpack PJSIP (e.g. “pjproject-1.10.zip” from http://www.pjsip.org/download.htm)
4. Download the GreenJ source code and unpack it or clone our GitHub repository.
5. Open the VS2008 solution file “greenj.sln”
6. Either change the path to pjsip in the property manager (6A) or copy all pjsip libs to the GreenJ source code (6B).
    1. Change the property PJSIP_INCLUDE_DIR in the Visual Studio project: Property Manager > Debug and Release | Win32 > greenj > Properties > User Macros > PJSIP_INCLUDE_DIR.
    2. Or copy the following folders from “path/to/pjproject-1.xx” to “path/to/greenj/lib/win32/pjsip”:
        - pjlib
        - pjlib-util
        - pjmedia
        - pjnath
        - pjsip
        - third_party
7. Build the solution in Debug or Release mode.

---

Here are some additional notes for deployment:

**Windows Deployment**

The following DLL files are needed by Qt (e.g. in the program folder):
QtCore4.dll, QtGui4.dll, QtNetwork4.dll, QtWebKit4.dll, phonon4.dll
The files can be found in “path/to/Qt/bin”.
We also recommend to deploy an additional folder called “imageformats” (located in “path/to/Qt/plugins”) with GreenJ, otherwise the integrated browser might not be able to display various image files.
Note: When GreenJ is started for the first time, a new folder called “.greenj” is created in your HOME directory and the file “settings.conf” will be created (e.g. “C:\Users\li\.greenj\settings.conf”).

**Comment by running8Man** [comment]
Thank you for your reply !
